apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ca-trust
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sylesh-687/private-ca-trust-injection.git
      revision: HEAD
      directories:
      - path: ca-trust/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL:  https://github.com/sylesh-687/private-ca-trust-injection.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /status
      syncPolicy:
        automated:
          prune: true
          selfHeal: true