apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-private-ca
spec:
  rules:
    - name: inject-ca-bundle
      match:
        resources:
          kinds:
            - Pod
            - Deployment
            - StatefulSet
            - DaemonSet
            - Job
            - CronJob
          selector:
            matchLabels:
              inject-ca: "true"
      mutate:
        patchStrategicMerge:
          spec:
            volumes:
              - name: custom-ca
                configMap:
                  name: ca-bundle
            containers:
              - (name): "*"
                env:
                - name: SSL_CERT_FILE
                  value: /etc/ssl/certs/ca-certificates.crt
                - name: REQUESTS_CA_BUNDLE
                  value: /etc/ssl/certs/ca-certificates.crt
                volumeMounts:
                  - mountPath: /etc/ssl/certs/ca-certificates.crt
                    name: custom-ca
                    subPath: trust-bundle.pem
                  - mountPath: /etc/ssl/cert.pem
                    name: custom-ca
                    subPath: trust-bundle.pem 