apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      key: ca.crt
      name: cert-for-nginx-secret
  target:
    configMap:
      key: trust-bundle.pem